### ISSUE TITLE
Add new facility ports permissions for network model update 2a

### ISSUE THREAD

**Issue by ibaldin** [fabric-testbed/fabric-core-api#25]
Net.FacilityPort.Cloud-Facility-GCP "Google Cloud Platform"

Net.FacilityPort.Cloud-Facility-AWS "Amazon Web Services"

Net.FacilityPort.Chameleon-TACC "Chameleon@TACC Production"

Net.FacilityPort.Cloud-Facility-Azure-Gov "Microsoft Azure Gov Cloud"

Net.FacilityPort.Cloud-Facility-Azure "Microsoft Azure Cloud"

re: FIP-383

**Comment by mjstealey** [comment]
done, closing
